name: Daily Crawl

on:
  schedule:
    - cron: "0 23 * * *"   # 매일 한국시간 오전 8시 실행
  workflow_dispatch:        # 수동 실행도 가능

jobs:
  crawl:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run crawler
        run: python crawler.py --out data/집회_정보.csv

      - name: Commit and push results
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add data/집회_정보.csv
          git commit -m "Update 집회_정보.csv on $(date '+%Y-%m-%d')" || echo "No changes to commit"
          git push
