name: Daily Crawl

on:
  schedule:
    - cron: "0 23 * * *"   # 오전 8시 (KST)
    - cron: "0 11 * * *"   # 오후 8시 (KST)
  workflow_dispatch:

permissions:
  contents: write

jobs:
  crawl:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.9"
      - run: pip install -r requirements.txt

      - name: Run crawler (morning or evening)
        run: |
          if [ "$(date +'%H')" = "23" ]; then
            echo ">>> Morning crawl (KST 08:00)"
            python crawler.py
          else
            echo ">>> Evening crawl (KST 20:00)"
            python integrated_crawler.py
          fi

      - name: Commit and push results
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add data/
          git commit -m "Crawl run at $(date -u +'%Y-%m-%d %H:%M:%S UTC')" || echo "No changes to commit"
          git push
